def currency(fromcurr, amount, tocurr):
    match fromcurr.upper():
        case "USD" | "USDOLLAR":
            match tocurr.upper():
                case "EURO" | "EUR":
                    return amount * 0.851
                case "POUND" | "GBP":
                    return amount * 0.745
                case "SWISSFRANC" | "CHF":
                    return amount * 0.793
                case "YEN" | "JPY":
                    return amount * 155.159
                case "Yuan" | "CNY":
                    return amount * 7.059
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 9.236
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 10.063
                case "DANISHKRONE" | "DKK":
                    return amount * 6.352
                case "RUB" | "RUBLE":
                    return amount  * 84.067
                case "PULA" | "BWP":
                    return amount * 13.91
                case "CAD" | "CANADIANDOLLAR":
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "CAD" | "CANADIANDOLLAR":
            match tocurr.upper():
                case "USD" | "USDOLLAR":
                    return amount * 1
                case "EURO" | "EUR":
                    return amount * 1
                case "POUND" | "GBP":
                    return amount * 1
                case "SWISSFRANC" | "CHF":
                    return amount * 1
                case "YEN" | "JPY":
                    return amount * 1
                case "Yuan" | "CNY":
                    return amount * 1
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 1
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 1
                case "DANISHKRONE" | "DKK":
                    return amount * 1
                case "RUB" | "RUBLE":
                    return amount * 1
                case "PULA" | "BWP":
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "EUR" | "EURO":
            match tocurr.upper():
                case "USD" | "USDOLLAR":
                    return amount * 1.176
                case "POUND" | "GBP":
                    return amount * 0.874
                case "SWISSFRANC" | "CHF":
                    return amount * 0.934
                case "YEN" | "JPY":
                    return amount * 174.703
                case "Yuan" | "CNY":
                    return amount * 8.333
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 11.061
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 11.716
                case "DANISHKRONE" | "DKK":
                    return amount * 7.464
                case "RUB" | "RUBLE":
                    return amount * 98.219
                case "PULA" | "BWP":
                    return amount * 15.990
                case "CAD" | "CANADIANDOLLAR":
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "GBP" | "POUND":
            match tocurr.upper():
                case "USD" | "USDOLLAR":
                    return amount * 1.343
                case "EURO" | "EUR":
                    return amount * 1.144
                case "SWISSFRANC" | "CHF":
                    return amount * 1.068
                case "YEN" | "JPY":
                    return amount * 199.783
                case "Yuan" | "CNY":
                    return amount * 9.526
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 12.655
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 13.402
                case "DANISHKRONE" | "DKK":
                    return amount * 8.537
                case "RUB" | "RUBLE":
                    return amount * 112.295
                case "PULA" | "BWP":
                    return amount * 18.298
                case "CAD" | "CANADIANDOLLAR":
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "CHF" | "SWISSFRANC":
            match tocurr.upper():
                case "USD" | "USDOLLAR":
                    return amount * 1.261
                case "EURO" | "EUR":
                    return amount * 1.070
                case "POUND" | "GBP":
                    return amount * 0.936
                case "YEN" | "JPY":
                    return amount * 186.959
                case "Yuan" | "CNY":
                    return amount * 8.914
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 11.839
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 12.535
                case "DANISHKRONE" | "DKK":
                    return amount * 7.988
                case "RUB" | "RUBLE":
                    return amount * 105.040
                case "PULA" | "BWP":
                    return amount * 17.087
                case "CAD" | "CANADIANDOLLAR":
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "JPY" | "YEN":
            match tocurr.upper():
                case "USD" | "USDOLLAR":
                    return amount * 0.0064
                case "EURO" | "EUR":
                    return amount * 0.0057
                case "POUND" | "GBP":
                    return amount * 0.0050
                case "SWISSFRANC" | "CHF":
                    return amount * 0.0053
                case "Yuan" | "CNY":
                    return amount * 0.048
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 0.063
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 0.067
                case "DANISHKRONE" | "DKK":
                    return amount * 0.043
                case "RUB" | "RUBLE":
                    return amount * 0.561
                case "PULA" | "BWP":
                    return amount * 0.092
                case "CAD" | "CANADIANDOLLAR":
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "CNY" | "YUAN":
            match tocurr.upper():
                case "USD" | "USDOLLAR":
                    return amount * 0.142
                case "EURO" | "EUR":
                    return amount * 0.120
                case "POUND" | "GBP":
                    return amount * 0.105
                case "SWISSFRANC" | "CHF":
                    return amount * 0.112
                case "YEN" | "JPY":
                    return amount * 20.975
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 1.328
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 1.406
                case "DANISHKRONE" | "DKK":
                    return amount * 0.896
                case "RUB" | "RUBLE":
                    return amount * 11.775
                case "PULA" | "BWP":
                    return amount * 1.916
                case "CAD" | "CANADIANDOLLAR":
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "SWEDEDISHKRONA" | "SEK":
            match tocurr.upper():
                case "USD" | "USDOLLAR":
                    return amount * 0.108
                case "EURO" | "EUR":
                    return amount * 0.090
                case "POUND" | "GBP":
                    return amount * 0.079
                case "SWISSFRANC" | "CHF":
                    return amount * 0.085
                case "YEN" | "JPY":
                    return amount * 15.798
                case "Yuan" | "CNY":
                    return amount * 0.753
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 1.059
                case "DANISHKRONE" | "DKK":
                    return amount * 0.675
                case "RUB" | "RUBLE":
                    return amount * 8.862
                case "PULA" | "BWP":
                    return amount * 1.439
                case "CAD" | "CANADIANDOLLAR":
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "NOK" | "NORWEGIANKRONE":
            match tocurr.upper():
                case "USD" | "USDOLLAR":
                    return amount * 0.099
                case "EURO" | "EUR":
                    return amount * 0.085
                case "POUND" | "GBP":
                    return amount * 0.075
                case "SWISSFRANC" | "CHF":
                    return amount * 0.080
                case "YEN" | "JPY":
                    return amount * 14.911
                case "Yuan" | "CNY":
                    return amount * 0.711
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 0.944
                case "DANISHKRONE" | "DKK":
                    return amount * 0.637
                case "RUB" | "RUBLE":
                    return amount * 8.368
                case "PULA" | "BWP":
                    return amount * 1.357
                case "CAD" | "CANADIANDOLLAR":
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "DANISHKRONE" | "DKK":
            match tocurr.upper():
                case "USD" | "USDOLLAR": 
                    return amount * 0.156
                case "EURO" | "EUR":
                    return amount * 0.134
                case "POUND" | "GBP":
                    return amount * 0.117
                case "SWISSFRANC" | "CHF":
                    return amount * 0.125
                case "YEN" | "JPY":
                    return amount * 23.404
                case "Yuan" | "CNY":
                    return amount * 1.116
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 1.482
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 1.570
                case "RUB" | "RUBLE":
                    return amount * 13.128
                case "PULA" | "BWP":
                    return amount * 2.141
                case "CAD" | "CANADIANDOLLAR": 
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "RUB" | "RUBLE":
            match tocurr.upper():
                case "USD" | "USDOLLAR": 
                    return amount * 0.012
                case "EURO" | "EUR":
                    return amount * 0.010
                case "POUND" | "GBP":
                    return amount * 0.009
                case "SWISSFRANC" | "CHF":
                    return amount * 0.001
                case "YEN" | "JPY":
                    return amount * 1.782
                case "Yuan" | "CNY":
                    return amount * 0.085
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 0.113
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 1.120
                case "DANISHKRONE" | "DKK":
                    return amount * 0.076
                case "PULA" | "BWP":
                    return amount * 0.162
                case "CAD" | "CANADIANDOLLAR": 
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case "BWP" | "PULA":
            match tocurr.upper():
                case "USD" | "USDOLLAR":
                    return amount * 0.073
                case "EURO" | "EUR":
                    return amount * 0.063
                case "POUND" | "GBP":
                    return amount * 0.055
                case "SWISSFRANC" | "CHF":
                    return amount * 0.059
                case "YEN" | "JPY":
                    return amount * 10.91
                case "YUAN" | "CNY":
                    return amount * 0.520
                case "SWEDEDISHKRONA" | "SEK":
                    return amount * 0.691
                case "NORWEGIANKRONE" | "NOK":
                    return amount * 0.732
                case "DANISHKRONE" | "DKK":
                    return amount * 0.466
                case "RUB" | "RUBLE":
                    return amount * 6.157
                case "CAD" | "CANADIANDOLLAR":
                    return amount * 1
                case _:
                    return "Unsupported target currency"
        case _:
            return "Unsupported source currency"